# Generated by Django 6.0.7 on 2026-08-01 18:42

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('expense', 'Chi tiêu'), ('income', 'Thu nhập')], db_index=True, max_length=10)),
                ('icon', models.CharField(default='💰', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('expense', 'Chi tiêu'), ('income', 'Thu nhập')], db_index=True, default='expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('is_special', models.BooleanField(default=False, help_text='Người dùng xác nhận đây là khoản chi đặc biệt (bỏ qua cảnh báo bất thường)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=core.models.expense_image_upload_path)),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to=core.models.expense_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_label', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.category')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.expenseimage')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'user'], name='core_catego_type_3989e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='uq_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='core_expens_user_id_84343e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'type', 'date'], name='core_expens_user_id_8ec438_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='core_expens_user_id_e92993_idx'),
        ),
    ]
