# Generated by Django 6.0.7 on 2026-08-01 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notified_80', models.BooleanField(default=False)),
                ('notified_100', models.BooleanField(default=False)),
                ('notified_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='budgets_bud_user_id_39ca25_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='uq_budget_period')],
            },
        ),
    ]
