# Generated by Django 6.0.7 on 2026-08-01 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('budget_80', 'Ngân sách đạt 80%'), ('budget_100', 'Ngân sách đạt 100%'), ('budget_over', 'Vượt ngân sách'), ('goal_reached', 'Đạt mục tiêu tiết kiệm'), ('anomaly', 'Chi tiêu bất thường'), ('ai_tip', 'Gợi ý AI'), ('system', 'Hệ thống')], default='system', max_length=20)),
                ('level', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('danger', 'Nguy hiểm'), ('success', 'Thành công')], default='info', max_length=10)),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
